administracion/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from users import views as user_views
from mensajes import views as mensajes_views
from cores import views as cores_views
from polads import views as polads_views

urlpatterns = [
    # HOME
    path('admin/', admin.site.urls),
    path('', views.home, name='home-page'),
    path('dudas/', views.dudas, name='dudas'),
    path('contacto/', views.contacto, name='contacto'),

    # USUARIOS
    path('sendjson/', user_views.send_json, name='send_json'),
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),

    # PASSWORDS
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name="password_reset_complete"),

    path('profile/', user_views.profile, name="profile"),
    path('profile-update/', user_views.profile_update, name="profile-update"),

    # MENSAJES
    path('mis-mensajes/', mensajes_views.mis_mensajes, name="mis-mensajes"),
    path('nuevo-mensaje/', mensajes_views.nuevo_mensaje, name="nuevo-mensaje"),
    path('ver-mensaje/<int:mensaje>/', mensajes_views.mensaje_completo, name="mensaje-completo"),

    # CORES
    path('agregar-cores/', cores_views.agregar_cores, name="agregar-cores"),
    path('ver-cores/', cores_views.ver_cores, name="ver-cores"),
    path('cupo-cores/', cores_views.cupo_cores, name="cupo-cores"),
    path('deletecores/<int:field>/', cores_views.deletecores, name="delete-cores"),
    path('rendir-cores/', cores_views.rendir_cores, name="rendir-cores"),

    # POLADS
    path('nuevo-adicional/', polads_views.nuevo_adicional, name="nuevo-adicional"),
    path('mis-adicionales/', polads_views.mis_adicionales, name="mis-adicionales"),
    path('agregar-turnos/<str:pk>', polads_views.agregar_turnos, name="agregar-turnos"),
    path('deleteturno/<int:field>/', polads_views.deleteturno, name="delete-turno"),
    path('rendir-adicional/<str:pk>', polads_views.rendir_adicional, name="rendir-adicional"),
    path('exportar/<str:pk>', polads_views.exportar, name="exportar"),
    path('calendario/<str:pk>/<int:year>/<int:month>/', polads_views.calendar, name="calendario"),

    path('descargar/<str:pk>', polads_views.descargar, name="descargar"),
]

cores/models.py
from django.db import models
from django.contrib.auth.models import User
from administracion.models import Efectivo, Comisaria
from users.models import Profile
from datetime import datetime

# Create your models here.

class Cores(models.Model):

    OPERATIVAS = 'OP'
    CHOFERES = 'OP CHOF'
    NO_OPERATIVAS = 'NO OP'

    TIPO_CHOICES = [
        (OPERATIVAS, 'OPERATIVAS'),
        (NO_OPERATIVAS, 'NO OPERATIVAS'),
        (CHOFERES, 'OPERATIVAS CHOFERES'),
    ]

    ingreso = models.DateTimeField(null=True)
    egreso = models.DateTimeField(null=True)
    efectivo = models.ForeignKey(Efectivo, on_delete=models.DO_NOTHING)
    tipo = models.CharField(max_length=13, choices=TIPO_CHOICES, default=OPERATIVAS)
    dependencia = models.ForeignKey(Comisaria, default=None, on_delete=models.DO_NOTHING)

    @property
    def get_diff(self):
        return int((self.egreso - self.ingreso).total_seconds()/60/60)

    def __str__(self):
        return f'{self.ingreso} a {self.egreso}: {self.efectivo}. Cantidad de horas: {self.get_diff}.'

cores/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Cores
from administracion.models import Efectivo
from datetime import datetime

# form for add new cores

class AgregarCores(forms.ModelForm):

    ingreso = forms.DateTimeField()
    egreso = forms.DateTimeField()
    efectivo = forms.CharField()

    class Meta:
        model = Cores
        fields = '__all__'
        exclude = ['dependencia']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        e_id = self.initial.get('efectivo', None)
        if e_id:
            self.initial['efectivo'] = Efectivo.objects.get(id=_id).efectivo_nombre

        self.fields['ingreso'].widget.attrs['type'] = 'datetime'
        self.fields['egreso'].widget.attrs['type'] = 'datetime'

    def clean(self):
        try:
            e = Efectivo.objects.get(efectivo_nombre=self.cleaned_data['efectivo'])
        except Efectivo.DoesNotExist:
            pass
        self.cleaned_data['efectivo'] = e

        return self.cleaned_data  # Return self.cleaned_data at the end of clean()

cores/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import AgregarCores
from .models import Cores
from administracion.models import Efectivo, Comisaria
from polads.models import Turno
from users.models import Profile
from django.http import JsonResponse
from django.core import serializers
from datetime import datetime, timedelta
from .filters import CoresFilter
from django.db.models import F, Sum, ExpressionWrapper, fields, Case, When, Value, CharField
from mensajes.models import Mensaje
from django.http import HttpResponse
from openpyxl import load_workbook
from openpyxl.writer.excel import save_virtual_workbook
from openpyxl.styles import Font, Alignment, Border, Side, PatternFill

# Create your views here.

# cores create record

@login_required
def agregar_cores(request):
    cores = Cores.objects.filter(dependencia=request.user.profile.administrador_de).order_by('-pk')[:10]
    dependencia = Comisaria.objects.get(dependencia=request.user.profile.administrador_de)
    errors = ''

    form = AgregarCores()

    if request.method == 'POST':
        form = AgregarCores(request.POST)

        if form.is_valid():

            instance = form.save(commit=False)

            # validación de turnos:

            all_turnos = Turno.objects.filter(efectivo=instance.efectivo)
            all_cores = Cores.objects.filter(efectivo=instance.efectivo)

            cant_cores = Cores.objects.filter(efectivo=instance.efectivo, ingreso__month=instance.ingreso.month).aggregate(
            horas=Sum(ExpressionWrapper(F('egreso') - F('ingreso'), output_field=fields.DurationField())))

            cant_polad = Turno.objects.filter(efectivo=instance.efectivo, ingreso__month=instance.ingreso.month).aggregate(
            horas=Sum(ExpressionWrapper(F('egreso') - F('ingreso'), output_field=fields.DurationField())))

            try:
                cant_cores = int(cant_cores.get('horas').total_seconds()/60/60)
            except:
                cant_cores = 0

            try:
                cant_polad = int(cant_polad.get('horas').total_seconds()/60/60)
            except:
                cant_polad = 0

            horas_mensuales = cant_cores + cant_polad

            es_valido = True

            for each in all_turnos:
                if instance.ingreso < each.egreso and each.ingreso < instance.egreso:
                        errors = 'Turno inválido para el efectivo ' + str(instance.efectivo) + ". Comunicate con " + str(each.polad.encargado) + "."
                        try:
                            administrador = Profile.objects.get(administrador_de=each.polad.comisaria)
                            mensaje = Mensaje(remitente=request.user, destinatario=administrador.user, mensaje=f'Mensaje automático. El usuario {request.user} ha intentado cargar un turno inválido de Cores para el efectivo {instance.efectivo} en Comisaría {request.user.profile.administrador_de}  el día {instance.ingreso.day}/{instance.ingreso.month} a partir de las {instance.ingreso.hour}.')
                            mensaje.save()
                        except Profile.DoesNotExist:
                            administrador = None
                        es_valido = False

            for each in all_cores:
                if instance.ingreso < each.egreso and each.ingreso < instance.egreso:
                        responsable = Profile.objects.get(administrador_de=each.dependencia)
                        errors = 'Turno inválido para el efectivo ' + str(instance.efectivo) + ". Comunicate con " + str(responsable.user) + "."
                        mensaje = Mensaje(remitente=request.user, destinatario=responsable.user, mensaje=f'Mensaje automático. El usuario {request.user} ha intentado cargar un turno inválido de Cores para el efectivo {instance.efectivo} en Comisaría {request.user.profile.administrador_de} el día {instance.ingreso.day}/{instance.ingreso.month} a partir de las {instance.ingreso.hour}.')
                        mensaje.save()
                        es_valido = False

            cant_instance = int((instance.egreso - instance.ingreso).seconds/3600)

            if instance.ingreso > instance.egreso:
                errors = "El ingreso no puede ser posterior al egreso."
                es_valido = False

            if cant_instance + cant_cores > 80:
                errors = "El efectivo ha superado el límite de horas para hacer Cores."
                es_valido = False

            # procesar turnos y horarios:

            if es_valido == True:

                if instance.ingreso.day == instance.egreso.day:
                    instance_valid = Cores(ingreso=instance.ingreso, egreso=instance.egreso, efectivo=instance.efectivo, tipo=instance.tipo, dependencia=dependencia)
                    instance_valid.save()

                elif instance.ingreso.day != instance.egreso.day:

                    if instance.egreso.month - instance.ingreso.month == 1 or instance.egreso.year - instance.ingreso.year == 1:
                        instance_valid_1 = Cores(ingreso=instance.ingreso, egreso=instance.egreso.replace(hour=00), efectivo=instance.efectivo, tipo=instance.tipo, dependencia=dependencia)
                        instance_valid_1.save()
                        instance_valid_2 = Cores(ingreso=instance.egreso.replace(hour=00), egreso=instance.egreso, efectivo=instance.efectivo, tipo=instance.tipo, dependencia=dependencia)
                        if instance_valid_2.egreso.hour == 00: pass
                        else: instance_valid_2.save()

                    if instance.egreso.day - instance.ingreso.day == 1:
                       instance_valid_1 = Cores(ingreso=instance.ingreso, egreso=instance.egreso.replace(hour=00), efectivo=instance.efectivo, tipo=instance.tipo, dependencia=dependencia)
                       instance_valid_1.save()
                       instance_valid_2 = Cores(ingreso=instance.egreso.replace(hour=00), egreso=instance.egreso, efectivo=instance.efectivo, tipo=instance.tipo, dependencia=dependencia)
                       if instance_valid_2.egreso.hour == 00: pass
                       else: instance_valid_2.save()

                    if instance.egreso.day - instance.ingreso.day > 1:
                        delta = instance.egreso - instance.ingreso
                        instance_valid_1 = Cores(ingreso=instance.ingreso, egreso=instance.ingreso.replace(day=instance.ingreso.day + 1, hour=00), efectivo=instance.efectivo, tipo=instance.tipo, dependencia=dependencia)
                        instance_valid_1.save()
                        for i in range(delta.days):
                            day = instance.ingreso + timedelta(days=i)
                            instance_valid_2 = Cores(ingreso=day.replace(day=day.day + 1, hour=00), egreso=day.replace(day=day.day + 2, hour=00), efectivo=instance.efectivo, tipo=instance.tipo, dependencia=dependencia)
                            if instance_valid_2.ingreso.day == instance.egreso.day: pass
                            else: instance_valid_2.save()
                        instance_valid_3 = Cores(ingreso=instance.egreso.replace(hour=00), egreso=instance.egreso, efectivo=instance.efectivo, tipo=instance.tipo, dependencia=dependencia)
                        instance_valid_3.save()

        else:
            print(form.errors.items())

    context = {'cores': cores, 'form': form, 'errors': errors}
    return render(request, 'cores/agregar_cores.html', context)

# cores delete record

@login_required
def deletecores(request, field):
    previous_page = request.META['HTTP_REFERER']
    corestodelete = Cores.objects.get(id=field)
    corestodelete.delete()
    return redirect(previous_page)

# view cores by filter

@login_required
def ver_cores(request):
    cores = Cores.objects.filter(dependencia=request.user.profile.administrador_de).order_by('-ingreso')
    myFilter = CoresFilter(request.GET, queryset=cores)
    cores = myFilter.qs
    context = {'cores': cores, 'myFilter': myFilter}
    return render(request, 'cores/ver_cores.html', context)

# cupo cores

@login_required
def cupo_cores(request):
    today = datetime.now()

    cores = Cores.objects.filter(dependencia=request.user.profile.administrador_de, ingreso__month=today.month).annotate(
    custom_order_1=Case(
    When(efectivo__efectivo_jerarquia='CRIO', then=Value(1)),
    When(efectivo__efectivo_jerarquia='SUBCRIO', then=Value(2)),
    When(efectivo__efectivo_jerarquia='PPAL', then=Value(3)),
    When(efectivo__efectivo_jerarquia='OI', then=Value(4)),
    When(efectivo__efectivo_jerarquia='OSI', then=Value(5)),
    When(efectivo__efectivo_jerarquia='OA', then=Value(6)),
    When(efectivo__efectivo_jerarquia='OSA', then=Value(7)),
    When(efectivo__efectivo_jerarquia='MAYOR', then=Value(8)),
    When(efectivo__efectivo_jerarquia='CAP', then=Value(9)),
    When(efectivo__efectivo_jerarquia='TTE1ERO', then=Value(10)),
    When(efectivo__efectivo_jerarquia='TTE', then=Value(11)),
    When(efectivo__efectivo_jerarquia='SUBTTE', then=Value(12)),
    When(efectivo__efectivo_jerarquia='SGTO', then=Value(13)),
    When(efectivo__efectivo_jerarquia='OFL', then=Value(14)),
    output_field=CharField())).order_by('custom_order_1', 'efectivo__efectivo_legajo').values(
    'efectivo__efectivo_item', 'efectivo__efectivo_nombre', 'efectivo__efectivo_legajo', 'efectivo__efectivo_jerarquia', 'tipo').annotate(
    horas=Sum(ExpressionWrapper(F('egreso') - F('ingreso'), output_field=fields.DurationField())))


    # OPERATIVAS

    cupo_operativas = Cores.objects.filter(dependencia=request.user.profile.administrador_de, ingreso__month=today.month, tipo='OP').aggregate(
    horas=Sum(ExpressionWrapper(F('egreso') - F('ingreso'), output_field=fields.DurationField())))

    try:
        cupo_operativas = int(cupo_operativas.get('horas').total_seconds()/60/60)
    except:
        cupo_operativas = 0

    # OPERATIVAS CHOFERES

cores/templates/cores/agregar_cores.html
{% extends 'administracion/base.html' %}

{% block scripts_local %}

<script>
 $(function () {
  $("#id_ingreso").datetimepicker({
      format: 'd/m/Y H:i',
  });
  $.datetimepicker.setLocale('es');
 });
</script>

<script>
 $(function () {
  $("#id_egreso").datetimepicker({
      format: 'd/m/Y H:i',
  });
  $.datetimepicker.setLocale('es');
 });
</script>

{% endblock scripts_local %}

{% block content %}
{% if user.profile.esta_autorizado == True %}

<section id="cores">

  <div class="container">
    <div class="row">
      <h3 align="center">{{ user.username }}</h3>
      <p align="center">Agregar horas CoReS</p>
    </div>
  </div>

  <hr>
  <br />
  <br />

  <div class="container">
      <div class="row">

        <div class="col-md-4 col-sm-4">
          <h5 align="center">Menú</h5>
          <hr>
          <h6 align="center">-<a href="{% url 'profile' %}"> Volver a mi escritorio</a></h6>
          <h6 align="center">-<a href="{% url 'ver-cores' %}"> Ver Cores</a></h6>
          <h6 align="center">-<a href="{% url 'cupo-cores' %}"> Ver Cupo</a></h6>
          <br />
        </div>

        <div class="col-md-8 col-sm-8">
          <form method="POST" autocomplete="off">
          {% csrf_token %}
              <input type="text" name="efectivo" value="" id="id_efectivo" /><br />
              <div align="center" class="col-md-4 col-sm-4">
                <h6>Ingreso:</h6> {{ form.ingreso }}
              </div>
              <div align="center" class="col-md-4 col-sm-4">
                <h6>Egreso:</h6> {{ form.egreso }}
              </div>
              <div align="center" class="col-md-4 col-sm-4">
                <h6>Tipo:</h6> {{ form.tipo }}
              </div>
              <div align="center" class="col-md-12 col-sm-12">
                <button type="submit">Agregar</button>
              </div>
              <div align="center" class="col-md-12 col-sm-4">
                <br /><h6 style="color:red">{{ errors }}</h6>
              </div>
          </form>
        </div>

      </div>
    </div>

<hr>

    <div class="container">
        <table>
          <tr>
            <th>Jerarquía</th>
            <th>Legajo</th>
            <th>Nombre</th>
            <th>Desde</th>
            <th>Hasta</th>
            <th>Tipo</th>
            <th>Horas</th>
            <th>Borrar</th>
          </tr>
          {% for field in cores %}
          <tr>
            <td>{{ field.efectivo.efectivo_jerarquia }}</td>
            <td>{{ field.efectivo.efectivo_legajo }}</td>
            <td>{{ field.efectivo }}</td>
            <td>{{ field.ingreso|date:'d/m/y - H:i'}}</td>
            <td>{{ field.egreso|date:'d/m/y - H:i'}}</td>
            <td>{{ field.tipo }}</td>
            <td>{{ field.get_diff }}</td>
            <td><a href="/deletecores/{{ field.id }}/">Borrar</a></td>
          </tr>
          {% endfor %}
        </table>
      </div>

</section>

{% else %}

<section id="cores">

  <div class="container">
    <div class="row">
      <h3 align="center">{{ user.username }}</h3>
      <p align="center">Tu cuenta está siendo revisada.</p>
    </div>
  </div>

{% endif %}
{% endblock content %}

cores/templates/cores/cupo_cores.html
{% extends 'administracion/base.html' %}

{% load timedelta_filter %}

{% block content %}
{% if user.profile.esta_autorizado == True %}

<section id="cores">

  <div class="container">
    <div class="row">
      <h3 align="center">{{ user.username }}</h3>
      <p align="center">Cupo de horas CoReS</p>
    </div>
  </div>

  <hr>
  <br />
  <br />

  <div class="container">
      <div class="row">

        <div class="col-md-4 col-sm-4">
          <h5 align="center">Menú</h5>
          <hr>
          <h6 align="center">-<a href="{% url 'profile' %}"> Volver a mi escritorio</a></h6>
          <h6 align="center">-<a href="{% url 'agregar-cores' %}"> Cargar Cores</a></h6>
          <h6 align="center">-<a href="{% url 'ver-cores' %}"> Ver Cores</a></h6>
          <br />
        </div>

        <div class="col-md-8 col-sm-8">
          <h5 align="center">Mes de {{ today|date:'F' }} de {{ today|date:'Y' }}: </h5>
          <hr>
        </div>
        <div class="col-md-4 col-sm-4">
          <h6 align="center">Cores Operativas: {{ cupo_operativas }}</h6>
          <h6 align="center">Cores Operativas Choferes: {{ cupo_operativas_choferes }}</h6>
          <h6 align="center">Cores No Operativas: {{ cupo_no_operativas }}</h6>
        </div>
        <div class="col-md-4 col-sm-4">
          <br />
          <a href="{% url 'rendir-cores' %}"><h6 align="center">RENDIR CORES</h6></a>
          <br />
        </div>

      </div>
    </div>

<hr>

    <div class="container">
        <table>
          <tr>
            <th>Item</th>
            <th>Jerarquía</th>
            <th>Legajo</th>
            <th>Nombre</th>
            <th>Tipo</th>
            <th>Horas</th>
          </tr>
          {% for field in cores|dictsortreversed:"tipo" %}
          <tr>
            <td>{{ field.efectivo__efectivo_item }}</td>
            <td>{{ field.efectivo__efectivo_jerarquia }}</td>
            <td>{{ field.efectivo__efectivo_legajo }}</td>
            <td>{{ field.efectivo__efectivo_nombre }}</td>
            <td>{{ field.tipo}}</td>
            <td>{{ field.horas|timedelta:"{hours_total}" }}</td>
          </tr>
          {% endfor %}
        </table>
      </div>

</section>

{% else %}

<section id="cores">

  <div class="container">
    <div class="row">
      <h3 align="center">{{ user.username }}</h3>
      <p align="center">Tu cuenta está siendo revisada.</p>
    </div>
  </div>

{% endif %}
{% endblock content %}

cores/templates/cores/ver_cores.html
{% extends 'administracion/base.html' %}

{% block scripts_local %}

<script>
 $(function () {
  $("#id_start_date").datetimepicker({
      timepicker: false,
      format: 'd/m/Y',
  });
 $.datetimepicker.setLocale('es');
 });
</script>

<script>
 $(function () {
  $("#id_end_date").datetimepicker({
    timepicker: false,
    format: 'd/m/Y',
  });
 $.datetimepicker.setLocale('es');
 });
</script>

{% endblock scripts_local %}

{% block content %}
{% if user.profile.esta_autorizado == True %}

<section id="cores">

  <div class="container">
    <div class="row">
      <h3 align="center">{{ user.username }}</h3>
      <p align="center">Ver horas CoReS</p>
    </div>
  </div>

  <hr>
  <br />
  <br />

  <div class="container">
      <div class="row">

        <div class="col-md-4 col-sm-4">
          <h5 align="center">Menú</h5>
          <hr>
          <h6 align="center">-<a href="{% url 'profile' %}"> Volver a mi escritorio</a></h6>
          <h6 align="center">-<a href="{% url 'agregar-cores' %}"> Cargar Cores</a></h6>
          <h6 align="center">-<a href="{% url 'cupo-cores' %}"> Cupo Cores</a></h6>
          <br />
        </div>

        <div class="col-md-8 col-sm-8">
          <form method="GET" autocomplete="off">
            <input type="text" name="efectivo" value="" id="id_efectivo" /><br />
            <div align="center" class="col-md-4 col-sm-4">
              <h6>A partir del:<br />(inclusive)</h6> {{ myFilter.form.start_date }}
            </div>
            <div align="center" class="col-md-4 col-sm-4">
              <h6>Hasta el:<br />(no inclusive)</h6> {{ myFilter.form.end_date }}
            </div>
            <div align="center" class="col-md-4 col-sm-4">
              <h6>Tipo:<br /><br /></h6> {{ myFilter.form.tipo }}
            </div>
            <div align="center" class="col-md-12 col-sm-12">
              <button type="submit">Buscar</button>
            </div>
          </form>
        </div>

      </div>
  </div>

<hr>

  <div class="container">
      <table>
        <tr>
          <th>Jerarquía</th>
          <th>Legajo</th>
          <th>Nombre</th>
          <th>Desde</th>
          <th>Hasta</th>
          <th>Tipo</th>
          <th>Horas</th>
          <th>Borrar</th>
        </tr>
        {% for field in cores %}
        <tr>
          <td>{{ field.efectivo.efectivo_jerarquia }}</td>
          <td>{{ field.efectivo.efectivo_legajo }}</td>
          <td>{{ field.efectivo }}</td>
          <td>{{ field.ingreso|date:'d/m/y - H:i' }}</td>
          <td>{{ field.egreso|date:'d/m/y - H:i' }}</td>
          <td>{{ field.tipo}}</td>
          <td>{{ field.get_diff }}</td>
          <td><a href="/deletecores/{{ field.id }}/">Borrar</a></td>
        </tr>
        {% endfor %}
      </table>
  </div>

</section>

{% else %}

<section id="cores">

  <div class="container">
    <div class="row">
      <h3 align="center">{{ user.username }}</h3>
      <p align="center">Tu cuenta está siendo revisada.</p>
    </div>
  </div>

{% endif %}
{% endblock content %}